[package]
name = "bazaar-server"
version = "0.1.0"
edition = "2021"

[dependencies]
mongodb = "2.0"
bson = "2.0"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
chrono = "0.4"
